/**
 * FlyAsh Intel — Optimization & Pareto Frontier Demo Data
 * 
 * NOTICE:
 * Represents simulated candidate solution vectors and non-dominated Pareto
 * frontiers generated by multi-objective evolutionary algorithms (NSGA-II)
 * for demonstration purposes. Calibrated around Indian Class F fly ash bounds.
 */

export interface CandidateSolution {
  id: string;
  rank: number;
  title: string;
  flyAsh: number;
  lime: number;
  gypsum: number;
  cement: number;
  sand: number;
  str: number;
  abs: number;
  co2: string;
  cost: string;
  status: string;
  batchWeight: string;
  isPareto: boolean;
  isFeasible: boolean;
}

export const DEMO_CANDIDATE_SOLUTIONS: CandidateSolution[] = [
  {
    id: 'OPT-01',
    rank: 1,
    title: 'High-Volume FaL-G (Recommended)',
    flyAsh: 65,
    lime: 18,
    gypsum: 5,
    cement: 0,
    sand: 12,
    str: 17.2,
    abs: 11.2,
    co2: '88% reduction',
    cost: '₹3.40 / brick',
    status: 'Optimal Pareto',
    batchWeight: '767 kg FA / 212 kg Lime / 59 kg Gyp',
    isPareto: true,
    isFeasible: true,
  },
  {
    id: 'OPT-02',
    rank: 2,
    title: 'Ultra High Fly Ash Infill',
    flyAsh: 72,
    lime: 14,
    gypsum: 4,
    cement: 0,
    sand: 10,
    str: 15.1,
    abs: 11.9,
    co2: '93% reduction',
    cost: '₹3.10 / brick',
    status: 'High Waste Util',
    batchWeight: '850 kg FA / 165 kg Lime / 47 kg Gyp',
    isPareto: true,
    isFeasible: true,
  },
  {
    id: 'OPT-03',
    rank: 3,
    title: 'Hybrid OPC Accelerated',
    flyAsh: 58,
    lime: 15,
    gypsum: 4,
    cement: 5,
    sand: 18,
    str: 21.4,
    abs: 9.8,
    co2: '68% reduction',
    cost: '₹3.85 / brick',
    status: 'Rapid Demold',
    batchWeight: '684 kg FA / 177 kg Lime / 59 kg OPC',
    isPareto: true,
    isFeasible: true,
  },
  {
    id: 'OPT-04',
    rank: 4,
    title: 'Structural Heavy-Duty Unit',
    flyAsh: 50,
    lime: 18,
    gypsum: 5,
    cement: 8,
    sand: 19,
    str: 24.2,
    abs: 8.9,
    co2: '58% reduction',
    cost: '₹4.20 / brick',
    status: 'Class 20 Heavy',
    batchWeight: '590 kg FA / 212 kg Lime / 94 kg OPC',
    isPareto: true,
    isFeasible: true,
  },
  {
    id: 'OPT-05',
    rank: 5,
    title: 'Max Waste Partition Unit',
    flyAsh: 78,
    lime: 12,
    gypsum: 3,
    cement: 0,
    sand: 7,
    str: 11.8,
    abs: 14.2,
    co2: '96% reduction',
    cost: '₹2.85 / brick',
    status: 'Partition Only',
    batchWeight: '920 kg FA / 141 kg Lime / 35 kg Gyp',
    isPareto: true,
    isFeasible: true,
  },

  // Feasible interior points
  {
    id: 'FEAS-01',
    rank: 6,
    title: 'Standard FaL-G Mix A',
    flyAsh: 60,
    lime: 16,
    gypsum: 4,
    cement: 0,
    sand: 20,
    str: 15.6,
    abs: 12.1,
    co2: '78% reduction',
    cost: '₹3.60 / brick',
    status: 'Feasible Interior',
    batchWeight: '708 kg FA / 189 kg Lime / 47 kg Gyp',
    isPareto: false,
    isFeasible: true,
  },
  {
    id: 'FEAS-02',
    rank: 7,
    title: 'Quarry Dust Secondary Blend',
    flyAsh: 55,
    lime: 15,
    gypsum: 5,
    cement: 0,
    sand: 25,
    str: 18.2,
    abs: 10.6,
    co2: '72% reduction',
    cost: '₹3.90 / brick',
    status: 'Feasible Interior',
    batchWeight: '649 kg FA / 177 kg Lime / 59 kg Gyp',
    isPareto: false,
    isFeasible: true,
  },

  // Dominated / Infeasible candidates
  {
    id: 'DOM-01',
    rank: 8,
    title: 'Excess Water Mix',
    flyAsh: 65,
    lime: 15,
    gypsum: 3,
    cement: 0,
    sand: 17,
    str: 9.8,
    abs: 16.8,
    co2: '88% reduction',
    cost: '₹3.35 / brick',
    status: 'Dominated / Non-conforming',
    batchWeight: '767 kg FA / 177 kg Lime / 35 kg Gyp',
    isPareto: false,
    isFeasible: false,
  },
  {
    id: 'DOM-02',
    rank: 9,
    title: 'Insufficient Lime Activator',
    flyAsh: 75,
    lime: 8,
    gypsum: 2,
    cement: 0,
    sand: 15,
    str: 8.4,
    abs: 17.5,
    co2: '94% reduction',
    cost: '₹2.95 / brick',
    status: 'Dominated / Suboptimal',
    batchWeight: '885 kg FA / 94 kg Lime / 24 kg Gyp',
    isPareto: false,
    isFeasible: false,
  },
];
